### ISSUE TITLE
Multiple Build Errors (iOS 8.3, XCode 6.3)

### ISSUE THREAD

**Issue by maddoggy1979** [DigitalLeaves/PlaceholderTextViewDemo#1]
Hi,
Loading your demo project and attempting to build it comes up with a bunch of errors.
Have you been able to update it to the current iOS8.3 beta 4? It does build in xcode 6.2.
Screenshot below.

![screen shot 2015-03-30 at 9 52 38 pm](https://cloud.githubusercontent.com/assets/8011491/6895784/1fcdb46a-d727-11e4-90b2-398c7ce58744.png)

**Comment by DigitalLeaves** [comment]
Hi,

I haven’t compiled it in XCode 6.3beta yet, but it would possibly have some compiling issues as swift has changed. It should be easy to fix ‘though.

Anyway, I will probably address this when XCode 6.3 becomes a stable release, not before.

Thanks!
