### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by moyoteg** [DigitalLeaves/PlaceholderTextViewDemo#2]
<img width="1290" alt="screen shot 2015-10-28 at 5 24 53 pm" src="https://cloud.githubusercontent.com/assets/574112/10806162/e34520e6-7d98-11e5-976c-35554c50ecbf.png">

Do you have a swift 2.0 version?

**Comment by DigitalLeaves** [comment]
Yes, I have it here, locked in my dev room, but I won't let it go out...

All joking aside. I haven't had time to change all my projects to Swift2, but I guess the 5 changes needed won't take you more than 3 minutes of your time, now would you? Anyway, I will try to change that as soon as I have some free time, thanks for pointing me out! :)

**Comment by moyoteg** [comment]
Haha ok, it could take me more time than that! haha :)
